type QBInvoiceInput = {
    "Apply Tax After Discount"?: string;
    "Balance"?: string;
    "Billing Address City"?: string;
    "Billing Address Country"?: string;
    "Billing Address Line 1"?: string;
    "Billing Address Line 2"?: string;
    "Billing Address Line 3"?: string;
    "Billing Address Postal Code"?: string;
    "Billing Address State"?: string;
    "Class"?: string;
    "Currency Code"?: string;
    "Custom Field Value (1)"?: string;
    "Custom Field Value (2)"?: string;
    "Custom Field Value (3)"?: string;
    "Customer"?: string;
    "Deposit"?: string;
    "Deposit To Account"?: string;
    "Discount Account"?: string;
    "Discount Amount"?: string;
    "Discount Percent"?: string;
    "Due Date"?: string;
    "Email"?: string;
    "Email BCC"?: string;
    "Email CC"?: string;
    "Email Status"?: string;
    "Enable CreditCard Payment"?: string;
    "Enable Intuit Payment"?: string;
    "Enable Online Payment"?: string;
    "EnableACHPayment"?: string;
    "Exchange Rate"?: string;
    "Invoice Date"?: string;
    "Invoice No"?: string;
    "Location"?: string;
    "Memo"?: string;
    "Message displayed on invoice"?: string;
    "Payment Reference No"?: string;
    "Payment Status"?: string;
    "Payment method"?: string;
    "Print Status"?: string;
    "Product/Service"?: string;
    "Product/Service Amount"?: string;
    "Product/Service Class"?: string;
    "Product/Service Description"?: string;
    "Product/Service Quantity"?: string;
    "Product/Service Rate"?: string;
    "Product/Service Taxable"?: string;
    "QbId"?: string;
    "Response"?: string;
    "Sales Tax Amount"?: string;
    "Sales Tax Code"?: string;
    "Sales Tax Percentage"?: string;
    "Service Date"?: string;
    "Ship Via"?: string;
    "Shipping"?: string;
    "Shipping Address City"?: string;
    "Shipping Address Country"?: string;
    "Shipping Address Line 1"?: string;
    "Shipping Address Line 2"?: string;
    "Shipping Address Line 3"?: string;
    "Shipping Address Postal Code"?: string;
    "Shipping Address State"?: string;
    "Shipping Date"?: string;
    "Show Sub Total"?: string;
    "Terms"?: string;
    "Tracking no"?: string;
};

export default QBInvoiceInput;